FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./main.go

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8090
CMD ["./main"]