apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-deployment
  labels:
    app: shipment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
      containers:
      - name: shipment-container
        image: dealanregistry.azurecr.io/dealan-shipment-service:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3007"
        envFrom:
        - configMapRef:
            name: dealan-config
        ports:
        - containerPort: 3007
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
spec:
  selector:
    app: shipment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007
  type: ClusterIP

