apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-deployment
  labels:
    app: shipment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
      containers:
      - name: shipment-container
        image: kelompokdealan/shipment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8094
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
spec:
  selector:
    app: shipment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8094
  type: ClusterIP