pipeline {
    agent any
    environment {
        DOCKER_HUB_USER = 'kelompokdealan' 
        IMAGE_NAME      = 'punishment-service'
        IMAGE_TAG       = 'latest'
    }
    stages {
        stage('Checkout Code') {
            steps { echo 'Mengambil kode terbaru dari Git...' }
        }
        stage('Unit Tests') {
            steps {
                dir('punishment-service') {
                    echo 'Menjalankan Go Unit Test...'
                    bat 'go test ./...'
                }
            }
        }
        stage('Lint/Vet') {
            steps {
                dir('punishment-service') {
                    echo 'Menjalankan Go Vet...'
                    bat 'go vet ./...'
                }
            }
        }
        stage('Build Image') {
            steps {
                dir('punishment-service') {
                    bat "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }
        stage('Functional Tests') {
            steps {
                dir('punishment-service') {
                    echo 'Menjalankan Functional Test...'
                    bat 'echo "Functional test belum diimplementasikan"'
                }
            }
        }
        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dealan-docker', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    bat "echo %PASS%| docker login -u %USER% --password-stdin"
                    bat "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploy di kubernetes') {
            steps {
                dir('punishment-service') {
                    echo 'Deploying to Kubernetes...'
                    bat 'kubectl apply -f punishment-k8s.yaml'
                }
            }
        }
        stage('Verify') {
            steps {
                dir('punishment-service') {
                    echo 'Verifying Deployment...'
                    bat 'kubectl rollout status deployment/punishment-service-deployment'
                }
            }
        }
    }
}