pipeline {
    agent any

    environment {
        IMAGE_NAME = "shakilaaulia245/map-route-service"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME% .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {

                    bat 'echo %DOCKER_TOKEN% | docker login -u shakilaaulia245 --password-stdin'

                    bat 'docker push %IMAGE_NAME%'
                }
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker stop map-route-service || exit 0'
                bat 'docker rm map-route-service || exit 0'

                bat 'docker run -d --name map-route-service -p 8085:8085 %IMAGE_NAME%'
            }
        }
    }
}