pipeline {
    agent any

    environment {
        DOCKER_USER  = 'shakilaaulia245'
        IMAGE_NAME   = 'shakilaaulia245/chat-service'
        CONTAINER_NAME = 'chat-service'
        PORT = '8087'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                dir('chat-service') {
                    sh 'go test ./... || true'
                }
            }
        }

        stage('Lint/Vet') {
            steps {
                dir('chat-service') {
                    sh 'go vet ./... || true'
                }
            }
        }

        stage('Build Image') {
            steps {
                dir('chat-service') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Functional Tests') {
            steps {
                sh 'docker stop $CONTAINER_NAME || true'
                sh 'docker rm $CONTAINER_NAME || true'

                sh 'docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME:latest'
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {

                    sh 'echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin'

                    sh 'docker push $IMAGE_NAME:latest'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('chat-service') {
                    sh 'kubectl apply --validate=false -f chat-k8s.yaml'
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl rollout status deployment/chat-deployment'
            }
        }
    }
}