pipeline {
    agent any

    environment {
        DOCKER_USER  = 'shakilaaulia245'
        IMAGE_NAME   = 'shakilaaulia245/chat-service'
        SERVICE_DIR  = 'chat-service'
        PORT         = '8087'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                bat "cd /d %SERVICE_DIR% && go test ./... || exit /b 0"
            }
        }

        stage('Lint/Vet') {
            steps {
                bat "cd /d %SERVICE_DIR% && go vet ./... || exit /b 0"
            }
        }

        stage('Build Image') {
            steps {
                bat "cd /d %SERVICE_DIR% && docker build -t %IMAGE_NAME%:latest ."
            }
        }

        stage('Functional Tests') {
            steps {
                bat "docker stop chat-service || exit /b 0"
                bat "docker rm chat-service || exit /b 0"

                bat "docker run -d --name chat-service -p %PORT%:%PORT% %IMAGE_NAME%:latest"
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {

                    bat "echo %DOCKER_TOKEN% | docker login -u %DOCKER_USER% --password-stdin"

                    bat "docker push %IMAGE_NAME%:latest"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat "cd /d %SERVICE_DIR% && kubectl apply -f chat-k8s.yaml"
            }
        }

        stage('Verify Deployment') {
            steps {
                bat "kubectl rollout status deployment/chat-deployment"
            }
        }
    }
}