pipeline {
    agent any

    environment {
        IMAGE_NAME = "shakilaaulia245/promo-service"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                dir('promo-service') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {

                    sh 'echo $DOCKER_TOKEN | docker login -u shakilaaulia245 --password-stdin'

                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop promo-service || true'
                sh 'docker rm promo-service || true'

                sh 'docker run -d --name promo-service -p 8086:8086 $IMAGE_NAME'
            }
        }
    }
}