pipeline {
    agent any

    environment {
        IMAGE_NAME = "shakilaaulia245/promo-service"
        CONTAINER_NAME = "promo-service"
        PORT = "8086"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean Docker') {
            steps {
                sh 'docker system prune -af || true'
                sh 'docker builder prune -af || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('promo-service') {
                    sh 'docker build --no-cache -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh 'echo $DOCKER_TOKEN | docker login -u shakilaaulia245 --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop $CONTAINER_NAME || true'
                sh 'docker rm $CONTAINER_NAME || true'
                sh 'docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME'
            }
        }

        stage('Verify') {
            steps {
                sh 'docker ps | grep $CONTAINER_NAME'
            }
        }
    }
}