apiVersion: apps/v1
kind: Deployment
metadata:
  name: promo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promo-service
  template:
    metadata:
      labels:
        app: promo-service
    spec:
      containers:
        - name: promo-service
          image: dealanregistry.azurecr.io/dealan-promo-service:latest
          env:
          - name: PORT
            value: "3014"
          envFrom:
          - configMapRef:
              name: dealan-config
          ports:
            - containerPort: 3014

---
apiVersion: v1
kind: Service
metadata:
  name: promo-service
spec:
  selector:
    app: promo-service
  ports:
    - port: 8080
      targetPort: 3014
  type: ClusterIP

