apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-review-service-deployment
  labels:
    app: rating-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-review-service
  template:
    metadata:
      labels:
        app: rating-review-service
    spec:
      containers:
      - name: rating-review-service
        image: dealanregistry.azurecr.io/dealan-rating-review-service:latest
        env:
        - name: PORT
          value: "3012"
        envFrom:
        - configMapRef:
            name: dealan-config
        ports:
        - containerPort: 3012
---
apiVersion: v1
kind: Service
metadata:
  name: rating-review-service
spec:
  selector:
    app: rating-review-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 3012
  type: ClusterIP


